version: '3'
services:
  ros-melodic:
    build: ./
    volumes:
      - ./workspace:/home/user/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    privileged: true
    network_mode: "host"
    ipc: host
    #runtime: nvidia
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      #- NVIDIA_VISIBLE_DEVICES=all
      #- NVIDIA_DRIVER_CAPABILITIES=all